profiles:
  default:
    components:
      time:
        description: "time-related functions including timezone conversion and timestamp generation"
        oci: ghcr.io/dineshdb/wasi-components/time:v0.1.0
        config:
          timezone: "UTC"
        env:
          TIMEZONE: "UTC"
          LOG_LEVEL: "info"
      fetch:
        description: "making web requests and fetching remote resources"
        oci: ghcr.io/dineshdb/wasi-components/fetch:v0.1.0
        env:
          HTTP_TIMEOUT: "30"
          MAX_REDIRECTS: "5"
          USER_AGENT: "wasmic-fetch/1.0"
      context7:
        description: "Resolving dependencies and libraries id"
        oci: ghcr.io/dineshdb/wasi-components/context7:v0.1.0
      markdown:
        description: "Manipulate markdown"
        oci: ghcr.io/dineshdb/wasi-components/markdown:latest
      fetch_markdown:
        description: "Fetch urls and convert them to markdown"
        oci: ghcr.io/dineshdb/wasi-components/fetch_markdown:latest
      brave_search:
        description: "Search the internet using brave search"
        oci: ghcr.io/dineshdb/wasi-components/brave_search:latest
        env:
          BRAVE_SEARCH_API_KEY: api-key
      myip:
        description: "Get your public ip"
        oci: ghcr.io/dineshdb/wasi-components/myip:latest
      fs:
        description: "file and directory operations"
        oci: ghcr.io/dineshdb/wasi-components/filesystem:v0.1.0
        cwd: /Users/dineshbhattarai/src/
        volumes:
          - host_path: "/tmp"
            guest_path: "/tmp"
            read_only: false
